use crate::types::{AABB, Vec3};
use crate::weapon::WeaponType;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FighterId {
    Kael,
    Knight,
    Zara,
    Magnus,
    Orin,
}

impl FighterId {
    pub const ALL: [FighterId; 5] = [
        FighterId::Kael,
        FighterId::Knight,
        FighterId::Zara,
        FighterId::Magnus,
        FighterId::Orin,
    ];
}

impl std::fmt::Display for FighterId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            FighterId::Kael => write!(f, "Kael"),
            FighterId::Knight => write!(f, "Knight"),
            FighterId::Zara => write!(f, "Zara"),
            FighterId::Magnus => write!(f, "Magnus"),
            FighterId::Orin => write!(f, "Orin"),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FighterStyle {
    Aggressive,
    Defensive,
    Technical,
}

#[derive(Debug, Clone)]
pub struct AttackData {
    pub name: &'static str,
    pub anim: &'static str,           // animation filename without extension
    pub damage_multiplier: f32,        // applied on top of weapon base damage
    pub startup_frames: u32,
    pub active_frames: u32,
    pub recovery_frames: u32,
    pub knockback_force: f32,
    pub hitbox_offset: Vec3,           // relative to fighter position + facing
    pub hitbox_half_extents: Vec3,
    pub launches: bool,                // sends opponent airborne
}

impl AttackData {
    pub fn total_frames(&self) -> u32 {
        self.startup_frames + self.active_frames + self.recovery_frames
    }
}

#[derive(Debug, Clone)]
pub struct MoveSet {
    pub light_attack: AttackData,
    pub heavy_attack: AttackData,
    pub special_attack: AttackData,
    pub mid_kick: AttackData,
    pub low_kick: AttackData,
    pub aerial: AttackData,
    pub combo_finisher: AttackData,
    pub super_attack: AttackData,
}

/// Maps game states to animation filenames (without extension).
#[derive(Debug, Clone)]
pub struct AnimationSet {
    pub dir: &'static str,
    pub idle: &'static str,
    pub run: &'static str,
    pub run_backward: &'static str,
    pub strafe_left: &'static str,
    pub strafe_right: &'static str,
    pub block: &'static str,
    pub hit_reaction: &'static str,
    pub knockdown: &'static str,
    pub getting_up: &'static str,
    pub death: &'static str,
    pub sweep_fall: &'static str,
}

#[derive(Debug, Clone)]
pub struct FighterData {
    pub id: FighterId,
    pub style: FighterStyle,
    pub max_health: f32,
    pub max_stamina: f32,
    pub move_speed: f32,
    pub dash_speed: f32,
    pub dash_frames: u32,
    pub defense: f32,          // damage reduction multiplier (lower = less damage taken)
    pub default_weapon: WeaponType,
    pub moveset: MoveSet,
    pub hurtbox: AABB,         // body hurtbox relative to position (origin at feet)
    pub animations: AnimationSet,
}

impl FighterData {
    pub fn get(id: FighterId) -> &'static FighterData {
        match id {
            FighterId::Kael => &KAEL,
            FighterId::Knight => &KNIGHT,
            FighterId::Zara => &ZARA,
            FighterId::Magnus => &MAGNUS,
            FighterId::Orin => &ORIN,
        }
    }
}

// ---------------------------------------------------------------------------
// Kael — Aggressive unarmed brawler (punches, kicks, capoeira)
// ---------------------------------------------------------------------------
static KAEL: FighterData = FighterData {
    id: FighterId::Kael,
    style: FighterStyle::Aggressive,
    max_health: 95.0,
    max_stamina: 110.0,
    move_speed: 6.0,
    dash_speed: 14.0,
    dash_frames: 9,
    defense: 1.0,
    default_weapon: WeaponType::Unarmed,
    moveset: MoveSet {
        light_attack: AttackData {
            name: "Cross Punch",
            anim: "Cross Punch",
            damage_multiplier: 1.0,
            startup_frames: 3,
            active_frames: 2,
            recovery_frames: 5,
            knockback_force: 2.5,
            hitbox_offset: Vec3::new(0.9, 0.8, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.3, 0.3),
            launches: false,
        },
        heavy_attack: AttackData {
            name: "Hook",
            anim: "Hook",
            damage_multiplier: 1.6,
            startup_frames: 8,
            active_frames: 4,
            recovery_frames: 10,
            knockback_force: 5.0,
            hitbox_offset: Vec3::new(0.8, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.4, 0.3),
            launches: false,
        },
        special_attack: AttackData {
            name: "Illegal Elbow",
            anim: "Illegal Elbow Punch",
            damage_multiplier: 2.0,
            startup_frames: 6,
            active_frames: 4,
            recovery_frames: 12,
            knockback_force: 6.0,
            hitbox_offset: Vec3::new(0.8, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.4, 0.3),
            launches: false,
        },
        mid_kick: AttackData {
            name: "Roundhouse Kick",
            anim: "Roundhouse Kick",
            damage_multiplier: 1.3,
            startup_frames: 5,
            active_frames: 3,
            recovery_frames: 8,
            knockback_force: 4.0,
            hitbox_offset: Vec3::new(1.0, 0.6, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.3, 0.4),
            launches: false,
        },
        low_kick: AttackData {
            name: "Leg Sweep",
            anim: "Leg Sweep",
            damage_multiplier: 1.1,
            startup_frames: 4,
            active_frames: 3,
            recovery_frames: 7,
            knockback_force: 3.0,
            hitbox_offset: Vec3::new(0.9, 0.2, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.3, 0.4),
            launches: false,
        },
        aerial: AttackData {
            name: "Flip Kick",
            anim: "Flip Kick",
            damage_multiplier: 1.8,
            startup_frames: 7,
            active_frames: 4,
            recovery_frames: 14,
            knockback_force: 7.0,
            hitbox_offset: Vec3::new(0.7, 1.2, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.7, 0.3),
            launches: true,
        },
        combo_finisher: AttackData {
            name: "Knee Jab",
            anim: "Knee Jab",
            damage_multiplier: 2.5,
            startup_frames: 3,
            active_frames: 5,
            recovery_frames: 12,
            knockback_force: 9.0,
            hitbox_offset: Vec3::new(0.8, 0.7, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.4, 0.3),
            launches: false,
        },
        super_attack: AttackData {
            name: "Capoeira",
            anim: "Capoeira",
            damage_multiplier: 3.0,
            startup_frames: 5,
            active_frames: 8,
            recovery_frames: 16,
            knockback_force: 12.0,
            hitbox_offset: Vec3::new(0.9, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.8, 0.6, 0.5),
            launches: false,
        },
    },
    hurtbox: AABB {
        min: Vec3::new(-0.35, 0.0, -0.3),
        max: Vec3::new(0.35, 1.75, 0.3),
    },
    animations: AnimationSet {
        dir: "kael",
        idle: "Idle",
        run: "Running",
        run_backward: "Walking Backwards",
        strafe_left: "Left Strafe Walking",
        strafe_right: "Right Strafe Walking",
        block: "Standing Dodge Backward",
        hit_reaction: "Hit Reaction",
        knockdown: "Knocked Out",
        getting_up: "Standing Up",
        death: "Falling Back Death",
        sweep_fall: "Sweep Fall",
    },
};

// ---------------------------------------------------------------------------
// Knight — Defensive sword & shield fighter
// ---------------------------------------------------------------------------
static KNIGHT: FighterData = FighterData {
    id: FighterId::Knight,
    style: FighterStyle::Defensive,
    max_health: 115.0,
    max_stamina: 90.0,
    move_speed: 4.0,
    dash_speed: 10.0,
    dash_frames: 12,
    defense: 0.85,
    default_weapon: WeaponType::SwordAndShield,
    moveset: MoveSet {
        light_attack: AttackData {
            name: "Sword Slash",
            anim: "Sword And Shield Slash",
            damage_multiplier: 1.0,
            startup_frames: 5,
            active_frames: 3,
            recovery_frames: 7,
            knockback_force: 4.0,
            hitbox_offset: Vec3::new(1.2, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.5, 0.3),
            launches: false,
        },
        heavy_attack: AttackData {
            name: "Heavy Slash",
            anim: "Sword And Shield Slash (3)",
            damage_multiplier: 1.8,
            startup_frames: 10,
            active_frames: 4,
            recovery_frames: 12,
            knockback_force: 6.0,
            hitbox_offset: Vec3::new(1.1, 1.0, 0.0),
            hitbox_half_extents: Vec3::new(0.8, 0.5, 0.3),
            launches: false,
        },
        special_attack: AttackData {
            name: "Shield Strike",
            anim: "Sword And Shield Attack",
            damage_multiplier: 2.0,
            startup_frames: 7,
            active_frames: 4,
            recovery_frames: 14,
            knockback_force: 8.0,
            hitbox_offset: Vec3::new(1.0, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.5, 0.4),
            launches: false,
        },
        mid_kick: AttackData {
            name: "MMA Kick",
            anim: "Mma Kick",
            damage_multiplier: 1.3,
            startup_frames: 6,
            active_frames: 3,
            recovery_frames: 9,
            knockback_force: 4.5,
            hitbox_offset: Vec3::new(1.0, 0.6, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.3, 0.4),
            launches: false,
        },
        low_kick: AttackData {
            name: "Groin Kick",
            anim: "Kick To The Groin",
            damage_multiplier: 1.2,
            startup_frames: 5,
            active_frames: 3,
            recovery_frames: 8,
            knockback_force: 3.5,
            hitbox_offset: Vec3::new(0.9, 0.3, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.3, 0.4),
            launches: false,
        },
        aerial: AttackData {
            name: "Drop Kick",
            anim: "Drop Kick",
            damage_multiplier: 1.8,
            startup_frames: 8,
            active_frames: 4,
            recovery_frames: 16,
            knockback_force: 7.5,
            hitbox_offset: Vec3::new(0.8, 1.1, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.6, 0.4),
            launches: true,
        },
        combo_finisher: AttackData {
            name: "Two Hand Combo",
            anim: "Two Hand Sword Combo",
            damage_multiplier: 2.8,
            startup_frames: 4,
            active_frames: 6,
            recovery_frames: 14,
            knockback_force: 10.0,
            hitbox_offset: Vec3::new(1.1, 1.0, 0.0),
            hitbox_half_extents: Vec3::new(0.8, 0.6, 0.4),
            launches: false,
        },
        super_attack: AttackData {
            name: "Double Kick Kip Up",
            anim: "Inverted Double Kick To Kip Up",
            damage_multiplier: 3.0,
            startup_frames: 6,
            active_frames: 7,
            recovery_frames: 18,
            knockback_force: 13.0,
            hitbox_offset: Vec3::new(0.8, 1.2, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.8, 0.5),
            launches: true,
        },
    },
    hurtbox: AABB {
        min: Vec3::new(-0.45, 0.0, -0.3),
        max: Vec3::new(0.45, 1.9, 0.3),
    },
    animations: AnimationSet {
        dir: "knight",
        idle: "Draw Sword 2",
        run: "Sword And Shield Run",
        run_backward: "Walking Backwards",
        strafe_left: "Left Strafe Walk",
        strafe_right: "Right Strafe Walking",
        block: "Block",
        hit_reaction: "Hit Reaction",
        knockdown: "Knocked Out",
        getting_up: "Knocked Out",
        death: "Falling Back Death",
        sweep_fall: "Sweep Fall",
    },
};

// ---------------------------------------------------------------------------
// Zara — Technical magic + martial arts fighter
// ---------------------------------------------------------------------------
static ZARA: FighterData = FighterData {
    id: FighterId::Zara,
    style: FighterStyle::Technical,
    max_health: 90.0,
    max_stamina: 120.0,
    move_speed: 5.5,
    dash_speed: 13.0,
    dash_frames: 8,
    defense: 1.05,
    default_weapon: WeaponType::Magic,
    moveset: MoveSet {
        light_attack: AttackData {
            name: "Punching",
            anim: "Punching",
            damage_multiplier: 0.9,
            startup_frames: 3,
            active_frames: 2,
            recovery_frames: 5,
            knockback_force: 2.5,
            hitbox_offset: Vec3::new(0.8, 0.8, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.3, 0.3),
            launches: false,
        },
        heavy_attack: AttackData {
            name: "Elbow Strike",
            anim: "Elbow Punching",
            damage_multiplier: 1.6,
            startup_frames: 7,
            active_frames: 3,
            recovery_frames: 9,
            knockback_force: 5.0,
            hitbox_offset: Vec3::new(0.7, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.4, 0.3),
            launches: false,
        },
        special_attack: AttackData {
            name: "Magic Bolt",
            anim: "standing 1H cast spell 01",
            damage_multiplier: 2.2,
            startup_frames: 8,
            active_frames: 4,
            recovery_frames: 14,
            knockback_force: 7.0,
            hitbox_offset: Vec3::new(1.2, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.8, 0.5, 0.4),
            launches: false,
        },
        mid_kick: AttackData {
            name: "MMA Kick",
            anim: "Mma Kick (1)",
            damage_multiplier: 1.3,
            startup_frames: 5,
            active_frames: 3,
            recovery_frames: 8,
            knockback_force: 4.0,
            hitbox_offset: Vec3::new(1.0, 0.6, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.3, 0.4),
            launches: false,
        },
        low_kick: AttackData {
            name: "Leg Sweep",
            anim: "Leg Sweep",
            damage_multiplier: 1.1,
            startup_frames: 4,
            active_frames: 3,
            recovery_frames: 7,
            knockback_force: 3.0,
            hitbox_offset: Vec3::new(0.9, 0.2, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.3, 0.4),
            launches: false,
        },
        aerial: AttackData {
            name: "Flip Kick",
            anim: "Flip Kick",
            damage_multiplier: 1.8,
            startup_frames: 7,
            active_frames: 4,
            recovery_frames: 14,
            knockback_force: 7.0,
            hitbox_offset: Vec3::new(0.7, 1.2, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.7, 0.3),
            launches: true,
        },
        combo_finisher: AttackData {
            name: "Meia Lua",
            anim: "Meia Lua De Compasso",
            damage_multiplier: 2.6,
            startup_frames: 4,
            active_frames: 6,
            recovery_frames: 12,
            knockback_force: 9.5,
            hitbox_offset: Vec3::new(0.9, 0.8, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.5, 0.4),
            launches: false,
        },
        super_attack: AttackData {
            name: "Magic Storm",
            anim: "Standing 2H Magic Area Attack 02",
            damage_multiplier: 3.2,
            startup_frames: 6,
            active_frames: 8,
            recovery_frames: 18,
            knockback_force: 13.0,
            hitbox_offset: Vec3::new(0.8, 1.0, 0.0),
            hitbox_half_extents: Vec3::new(1.0, 0.8, 0.6),
            launches: true,
        },
    },
    hurtbox: AABB {
        min: Vec3::new(-0.4, 0.0, -0.3),
        max: Vec3::new(0.4, 1.8, 0.3),
    },
    animations: AnimationSet {
        dir: "zara",
        idle: "Fighting Idle",
        run: "Sprint",
        run_backward: "Walking Backwards",
        strafe_left: "Left Strafe Walk",
        strafe_right: "Right Strafe Walk",
        block: "Blocking",
        hit_reaction: "Reaction",
        knockdown: "Sweep Fall",
        getting_up: "Getting Up",
        death: "Falling Back Death",
        sweep_fall: "Sweep Fall",
    },
};

// ---------------------------------------------------------------------------
// Magnus — Capoeira power fighter (mutant model, heavy hits)
// ---------------------------------------------------------------------------
static MAGNUS: FighterData = FighterData {
    id: FighterId::Magnus,
    style: FighterStyle::Aggressive,
    max_health: 105.0,
    max_stamina: 100.0,
    move_speed: 5.0,
    dash_speed: 12.0,
    dash_frames: 10,
    defense: 0.95,
    default_weapon: WeaponType::Unarmed,
    moveset: MoveSet {
        light_attack: AttackData {
            name: "Punching",
            anim: "Punching",
            damage_multiplier: 1.0,
            startup_frames: 4,
            active_frames: 3,
            recovery_frames: 6,
            knockback_force: 3.0,
            hitbox_offset: Vec3::new(0.9, 0.8, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.3, 0.3),
            launches: false,
        },
        heavy_attack: AttackData {
            name: "Mutant Punch",
            anim: "mutant punch",
            damage_multiplier: 1.8,
            startup_frames: 9,
            active_frames: 4,
            recovery_frames: 11,
            knockback_force: 6.5,
            hitbox_offset: Vec3::new(0.8, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.4, 0.3),
            launches: false,
        },
        special_attack: AttackData {
            name: "Flying Knee Combo",
            anim: "Flying Knee Punch Combo",
            damage_multiplier: 2.2,
            startup_frames: 7,
            active_frames: 5,
            recovery_frames: 16,
            knockback_force: 8.0,
            hitbox_offset: Vec3::new(0.7, 1.2, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.7, 0.3),
            launches: true,
        },
        mid_kick: AttackData {
            name: "Martelo",
            anim: "martelo 3",
            damage_multiplier: 1.4,
            startup_frames: 5,
            active_frames: 3,
            recovery_frames: 8,
            knockback_force: 4.5,
            hitbox_offset: Vec3::new(1.0, 0.7, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.4, 0.4),
            launches: false,
        },
        low_kick: AttackData {
            name: "Rasteira",
            anim: "rasteira 2",
            damage_multiplier: 1.2,
            startup_frames: 4,
            active_frames: 3,
            recovery_frames: 7,
            knockback_force: 3.5,
            hitbox_offset: Vec3::new(0.9, 0.2, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.3, 0.4),
            launches: false,
        },
        aerial: AttackData {
            name: "Mutant Jump Attack",
            anim: "mutant jump attack",
            damage_multiplier: 2.0,
            startup_frames: 7,
            active_frames: 5,
            recovery_frames: 14,
            knockback_force: 7.5,
            hitbox_offset: Vec3::new(0.7, 1.3, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.7, 0.4),
            launches: true,
        },
        combo_finisher: AttackData {
            name: "Queshada",
            anim: "queshada 2",
            damage_multiplier: 2.6,
            startup_frames: 4,
            active_frames: 5,
            recovery_frames: 13,
            knockback_force: 10.0,
            hitbox_offset: Vec3::new(0.9, 0.8, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.5, 0.4),
            launches: false,
        },
        super_attack: AttackData {
            name: "Meia Lua",
            anim: "meia lua de compasso",
            damage_multiplier: 3.0,
            startup_frames: 5,
            active_frames: 7,
            recovery_frames: 16,
            knockback_force: 12.0,
            hitbox_offset: Vec3::new(1.0, 1.0, 0.0),
            hitbox_half_extents: Vec3::new(0.8, 0.6, 0.5),
            launches: false,
        },
    },
    hurtbox: AABB {
        min: Vec3::new(-0.4, 0.0, -0.3),
        max: Vec3::new(0.4, 1.85, 0.3),
    },
    animations: AnimationSet {
        dir: "magnus",
        idle: "Idle",
        run: "Run",
        run_backward: "Walking Backwards",
        strafe_left: "Left Strafe Walk",
        strafe_right: "Right Strafe Walking",
        block: "Blocking",
        hit_reaction: "Hit Reaction",
        knockdown: "Fall Over",
        getting_up: "Standing Up",
        death: "Falling Back Death",
        sweep_fall: "Leg Sweep",
    },
};

// ---------------------------------------------------------------------------
// Orin — Capoeira balanced fighter (agile, combo-heavy)
// ---------------------------------------------------------------------------
static ORIN: FighterData = FighterData {
    id: FighterId::Orin,
    style: FighterStyle::Aggressive,
    max_health: 100.0,
    max_stamina: 105.0,
    move_speed: 5.5,
    dash_speed: 13.0,
    dash_frames: 9,
    defense: 1.0,
    default_weapon: WeaponType::Unarmed,
    moveset: MoveSet {
        light_attack: AttackData {
            name: "Punching",
            anim: "Punching",
            damage_multiplier: 1.0,
            startup_frames: 3,
            active_frames: 2,
            recovery_frames: 5,
            knockback_force: 2.5,
            hitbox_offset: Vec3::new(0.9, 0.8, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.3, 0.3),
            launches: false,
        },
        heavy_attack: AttackData {
            name: "Hook",
            anim: "Hook",
            damage_multiplier: 1.7,
            startup_frames: 8,
            active_frames: 4,
            recovery_frames: 10,
            knockback_force: 5.5,
            hitbox_offset: Vec3::new(0.8, 0.9, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.4, 0.3),
            launches: false,
        },
        special_attack: AttackData {
            name: "Backflip Uppercut",
            anim: "Back Flip To Uppercut",
            damage_multiplier: 2.0,
            startup_frames: 8,
            active_frames: 4,
            recovery_frames: 18,
            knockback_force: 7.5,
            hitbox_offset: Vec3::new(0.6, 1.3, 0.0),
            hitbox_half_extents: Vec3::new(0.5, 0.8, 0.3),
            launches: true,
        },
        mid_kick: AttackData {
            name: "Martelo",
            anim: "martelo 3",
            damage_multiplier: 1.3,
            startup_frames: 5,
            active_frames: 3,
            recovery_frames: 8,
            knockback_force: 4.0,
            hitbox_offset: Vec3::new(1.0, 0.6, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.3, 0.4),
            launches: false,
        },
        low_kick: AttackData {
            name: "Rasteira",
            anim: "rasteira 1",
            damage_multiplier: 1.1,
            startup_frames: 4,
            active_frames: 3,
            recovery_frames: 7,
            knockback_force: 3.0,
            hitbox_offset: Vec3::new(0.9, 0.2, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.3, 0.4),
            launches: false,
        },
        aerial: AttackData {
            name: "Armada",
            anim: "armada",
            damage_multiplier: 1.8,
            startup_frames: 6,
            active_frames: 4,
            recovery_frames: 13,
            knockback_force: 6.5,
            hitbox_offset: Vec3::new(0.8, 1.1, 0.0),
            hitbox_half_extents: Vec3::new(0.6, 0.6, 0.4),
            launches: true,
        },
        combo_finisher: AttackData {
            name: "Chapa Giratoria",
            anim: "chapa giratoria 2",
            damage_multiplier: 2.4,
            startup_frames: 3,
            active_frames: 6,
            recovery_frames: 12,
            knockback_force: 9.0,
            hitbox_offset: Vec3::new(0.9, 0.8, 0.0),
            hitbox_half_extents: Vec3::new(0.7, 0.5, 0.4),
            launches: false,
        },
        super_attack: AttackData {
            name: "Meia Lua",
            anim: "meia lua de compasso",
            damage_multiplier: 3.0,
            startup_frames: 5,
            active_frames: 7,
            recovery_frames: 16,
            knockback_force: 12.0,
            hitbox_offset: Vec3::new(1.0, 1.0, 0.0),
            hitbox_half_extents: Vec3::new(0.8, 0.6, 0.5),
            launches: false,
        },
    },
    hurtbox: AABB {
        min: Vec3::new(-0.35, 0.0, -0.3),
        max: Vec3::new(0.35, 1.75, 0.3),
    },
    animations: AnimationSet {
        dir: "orin",
        idle: "Idle",
        run: "Running",
        run_backward: "Walking Backwards",
        strafe_left: "Left Strafe Walking",
        strafe_right: "Right Strafe Walking",
        block: "Block",
        hit_reaction: "Reaction",
        knockdown: "Sweep Fall",
        getting_up: "Standing Up",
        death: "Fallen Idle",
        sweep_fall: "Sweep Fall",
    },
};
